name: refract
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
      - matplotlib
      - pandas
      - scipy
      - seaborn
      - lightgbm
      - pre-commit
      - pydantic
      - pyqt5-sip
      - pytest
      - pyyaml
      - scikit-learn
      - shap
      - stringdb
      - tensorboard
      - torch
      - torch-tb-profiler
      - torchaudio
      - torchvision
      - tqdm
      - xgboost
