name: corlab
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - pandas
  - scipy
  - seaborn
  - pip
  - pip:
      - lightgbm
      - pre-commit
      - pydantic
      - pyqt5-sip
      - pytest
      - pyyaml
      - scikit-learn
      - shap
      - stringdb
      - tensorboard
      - torch
      - torch-tb-profiler
      - torchaudio
      - torchvision
      - tqdm
      - xgboost
